- name: create installation template
  template: src=templates/create_db_filesystem.dbt.j2 dest=/home/oracle/create_db_{{ database_name }}.dbt mode=0700
  become: true
  become_user: oracle

- name: create database
  shell: "export ORACLE_HOME={{ oracle_home }}; {{ oracle_home }}/bin/dbca -silent -createdatabase -templatename /home/oracle/create_db_{{ database_name }}.dbt -gdbname {{ database_name }} -sid {{ database_name }} -syspassword {{ global_password }} -systempassword {{ global_password }} -dbsnmppassword {{ global_password }}"
  become: true
  become_user: oracle
