---

- name: test if /dev/sdb is a PV
  shell: pvdisplay -s /dev/sdb
  become: true
  register: is_sdb_pv
  ignore_errors: True

- name: make /dev/sdb a PV
  shell: pvcreate /dev/sdb
  become: true
  when: "is_sdb_pv.rc != 0"

- name: test if vg_oracle VG exists
  shell: vgdisplay vg_oracle
  become: true
  register: vg_oracle_exists
  ignore_errors: True

- name: create VG vg_oracle
  shell: vgcreate vg_oracle /dev/sdb
  become: true
  when: "vg_oracle_exists.rc != 0"

- name: test if lv_oracle LV exists
  shell: lvdisplay /dev/vg_oracle/lv_oracle
  become: true
  register: lv_oracle_exists
  ignore_errors: True

- name: create LV lv_oracle
  shell: lvcreate -n lv_oracle -L 20G /dev/vg_oracle
  become: true
  when: "lv_oracle_exists.rc != 0" 

- name: test if lv_oracle contains a xfs filesystem
  shell: blkid /dev/vg_oracle/lv_oracle
  become: true
  register: blkid_on_lv_oracle
  ignore_errors: True

- name: create xfs filesystem on lv_oracle
  shell: mkfs.xfs /dev/vg_oracle/lv_oracle
  become: true
  when: "'TYPE=\"xfs\"' not in blkid_on_lv_oracle.stdout"

- name: mount filesystem to /u01
  mount: name=/u01 src=/dev/vg_oracle/lv_oracle state=mounted fstype=xfs
  become: true

- name: set ownership correct for /u01 directory
  action: file dest="/u01" state=directory owner=oracle group=oinstall
  become: true
