---
- name: extend volume group vg_oracle with /dev/sdc
  lvg: vg=vg_oracle pvs=/dev/sdb,/dev/sdc
  become: true

- name: create logical volume lv_oradata in vg_oracle
  lvol: vg=vg_oracle lv=lv_oradata size=35g
  become: true

- name: create xfs filesystem in lv_oradata
  filesystem: fstype=xfs dev=/dev/vg_oracle/lv_oradata
  become: true

- name: mount filesystem to /u01/app/oracle/oradata
  mount: name=/u01/app/oracle/oradata src=/dev/vg_oracle/lv_oradata state=mounted fstype=xfs
  become: true

- name: set ownership correct for /u01/app/oracle/oradata directory
  action: file dest="/u01/app/oracle/oradata" state=directory owner=oracle group=oinstall
  become: true
