---

- name: create volume group vg_oracle using /dev/sdb
  lvg: vg=vg_oracle pvs=/dev/sdb
  become: true

- name: create logical volume lv_oracle in vg_oracle
  lvol: vg=vg_oracle lv=lv_oracle size=35g
  become: true

- name: create xfs filesystem in lv_oracle
  filesystem: fstype=xfs dev=/dev/vg_oracle/lv_oracle
  become: true

- name: mount filesystem to /u01
  mount: name=/u01 src=/dev/vg_oracle/lv_oracle state=mounted fstype=xfs
  become: true

- name: set ownership correct for /u01 directory
  action: file dest="/u01" state=directory owner=oracle group=oinstall
  become: true
